# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to Azure App Services using v3

on:
  push:
    branches:
      - master
  schedule: 
    - cron: "0 0/3 * * *"

jobs:
  build-and-deploy-dotnet-app:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Modify the sample app
        run: |
          cp -r ./__tests__/dotnetsampleapp dotnetapp
          current_utc_time=$(date -u +"%Y-%m-%d %H:%M:%S %Z")
          sed -i "s/<<<net-place-holder>>>/$current_utc_time/g" dotnetapp/Controllers/HelloController.cs

          echo "The placeholder has been replaced with current UTC time: $current_utc_time"

      - name: Set up .NET Core
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release dotnetapp/DOTNET_8_APP.csproj

      - name: dotnet publish
        run: dotnet publish dotnetapp/DOTNET_8_APP.csproj -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: .net-app
          path: myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383 # v3.0.8
        with:
          app-name: 'lwasv2-euap-dotnet-githubactionstest-v3'
          slot-name: 'Production'
          package: myapp
          publish-profile: ${{ secrets.LWASV2_EUAP_DOTNET_GITHUBACTIONSTEST_V3 }}

  build-and-deploy-node-app:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: modify Node.js App
        run: |
          cp -r ./__tests__/nodesampleapp nodeapp
          current_utc_time=$(date -u +"%Y-%m-%d %H:%M:%S %Z")
          sed -i "s/<<<node-place-holder>>>/$current_utc_time/g" nodeapp/server.js

          echo "The placeholder has been replaced with current UTC time: $current_utc_time"

      - name: Set up Node.js version
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '18.x'

      - name: npm ci, build, and test
        run: |
          cd nodeapp
          npm ci
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: node-app
          path: nodeapp
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@02a81bead70021f5284939794bcec79c271ab383 # v3.0.8
        with:
          app-name: 'lwasv2-euap-node-githubactions-v3'
          slot-name: 'Production'
          package: nodeapp
          publish-profile: ${{ secrets.LWASV2_EUAP_NODE_GITHUBACTIONS_V3 }}
