name: pr_check_windows_container_publishprofile

on:
<<<<<<< HEAD
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request_target:
=======
  pull_request:
>>>>>>> 0552a5a9 (Split workflows (#572))
    branches:
      - master
      - 'releases/*'

permissions:
  contents: read

jobs:
  validate-pr:
    name: Validate PR build
    runs-on: windows-latest
    steps:
    - name: Checkout from PR branch
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        path: 'webapps-deploy'
<<<<<<< HEAD
        ref: ${{ github.event.pull_request.head.ref }}
=======
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false
>>>>>>> 0552a5a9 (Split workflows (#572))

    - name: Installing dependencies and building latest changes in action
      run: |
        cd webapps-deploy
        npm ci
        npm run package