name: check_Webapp_python_linux

on:
  push:
    branches:
      - master
      - dev
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    braches:
      - users/balaga-gayatri/commit-message-fix
    paths-ignore:
      - '**.md'

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: pyhonwebapplima # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'         # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7'                  # set this to the python version to use
  CURRENT_BRANCH: azure/webapps-deploy@"${GITHUB_REF##*/}"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repository: Azure-Samples/pythonSample_thecatsaidno
#         token: ${{ secrets.GITSSHKEY }}
        ref: master
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        pwd
        echo "${{ env.CURRENT_BRANCH }}" 
        python -m pip install --upgrade pip
        pip install -r /home/runner/work/azure-actions-integration-tests/pythonSample_thecatsaidno/requirements.txt
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_SPN }}
    - name: Deploy Web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@"${GITHUB_REF##*/}"
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
