name: check_Webapp_Dotnet_Windows

on:
  push:
    branches:
      - master
      - dev
      - releases/*
    paths-ignore:
      - '**.md'
  pull_request:
    braches:
      - users/balaga-gayatri/commit-message-fix
    paths-ignore:
      - '**.md'

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: dotnetwebapplima    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NUGET_VERSION: '5.3.1'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: users/balaga-gayatri/commit-message-fix

    - name: Set Node.js 12.x for GitHub Action
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Run Npm Install for GitHub Action
      run: npm install

    - name: Build GitHub Action
      run: npm run build
      
    - uses: actions/checkout@master
      with:
        repository: Azure-Samples/dotnet-sample
#         token: ${{ secrets.GITSSHKEY }}
        ref: master

    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Run MSBuild
      run: msbuild .\SampleWebApplication.sln
    
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_SPN }}
  
    - name: 'Deploy to Azure WebApp'
      uses: ./
      id: webapps
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/SampleWebApplication/'
        
    - name: E2E Check HttpTrigger Result
      shell: pwsh
      run: |
        $i = 0
        while ($i -lt 10) {
          sleep 10
          $RESPONSE = $(curl "${{ steps.webapps.outputs.app-url }}/api/HttpTrigger")
          $RESULT = ($RESPONSE -eq "$env:GITHUB_SHA")
          if ($RESULT) {
            exit 0
          }
          $i = $i + 1
        }
        exit 1
        
  # For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
